refactor
KxSystems/docs pull request #325
Opened 2024-07-22 08:22 UTC by sshanks-kx

add month infinity

2024-08-02 17:12 UTC, natalietanner requested changes

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/rq.md
> +After writting data to disk, it will instruct a HDB to load the written data.
```suggestion
After writing data to disk, it instructs a HDB to load the written data.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/rq.md
> +The default RDB will store all of a days data in memory before end-of-day writting to disk. The host machines should be configured that all required resources
```suggestion
The default RDB stores all of a days data in memory before end-of-day writing to disk. The host machines should be configured that all required resources 
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/rq.md
> +A gateway process should control user queries and authorisation/authentication, using RDBs/RTEs/HDBs to retrieve the required information.
```suggestion
A gateway process should control user queries and authorization/authentication, using RDBs/RTEs/HDBs to retrieve the required information.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/rq.md
> +The end-of-day event is governed by the tickerplant process. The tickerplant calls the RDB [`.u.end`](#uend) function when this event occur.
```suggestion
The end-of-day event is governed by the tickerplant process. The tickerplant calls the RDB [`.u.end`](#uend) function when this event occurs.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/rq.md
> +!!! Note "The RDB should have tickerplant log available from a directory on the same machine. The RDB/tickerplant can be changed to reside on different hosts but this will entail the increased resour
```suggestion
!!! Note "The RDB should be able to access the tickerplant log from a directory on the same machine. The RDB/tickerplant can be changed to reside on different hosts but this increases the resources needed to transmit the log file contents over the network."
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/tickq.md
> +`tick.q` provides a starting point to most environments. The source code is freely avaialble and can be tailered to individual needs.
```suggestion
`tick.q` provides a starting point to most environments. The source code is freely available and can be tailored to individual needs.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/tickq.md
> +A schema file should be created to describe the data you plan to capture, by specifing the tables that will be populated by the tickerplant environment.
```suggestion
A schema file describes the data you plan to capture, by specifying the tables to be populated by the tickerplant environment. 
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/tickq.md
> +Real-time mode will process every tick as soon as they occur.
```suggestion
Real-time mode processes every tick as soon as they occur.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/tickq.md
> +This will be at the expense of tickerplant memory (required memory to hold several ticks) and increased latency that may occur between adding to the batch and sending.
```suggestion
This comes at the expense of tickerplant memory (required memory to hold several ticks) and increased latency that may occur between adding to the batch and sending. 
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/tickq.md
> +* if log file is found to be corrupt (size bigger than size of number of valid messages) an error will be returned
```suggestion
* if log file is found to be corrupt (size bigger than size of number of valid messages) an error is returned
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/tickq.md
> +Add each recieved message to batch and record message to tickerplant log. Batch will be published on running timer.
```suggestion
Add each received message to the batch and record message to the tickerplant log. Batch is published on running timer.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +Contains functions to allow clients to subscribe to all or subsets of available data, publishing to interested clients & alerting clients to events (i.e. end-of-day). Tracks client subscription inter
```suggestion
Contains functions to allow clients to subscribe to all or subsets of available data, publishing to interested clients and  alerting clients to events, for example, end-of-day. Tracks client subscription interest and removes client subscription details on their disconnection.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +To give the ability to publish data to any process, a few things need to be done:
```suggestion
To allow the ability to publish data to any process, do the following:
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +To add to a subscription (e.g. add more syms to a current subscription) the subscriber can call [`.u.add`](#uadd)).
```suggestion
If a subscriber calls `.u.sub` again, the current subscription is overwritten either for all tables (if a wildcard is used) or the specified table. 
To add to a subscription, for example, add more `syms` to a current subscription, the subscriber can call [`.u.add`](#uadd)).
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +Clients should define a [`upd`](rq.md#upd) function to receive updates, and [`.u.end`](rq.md#uend) function for end-of-day events
```suggestion
Clients should define a [`upd`](rq.md#upd) function to receive updates, and [`.u.end`](rq.md#uend) function for end-of-day events.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +| .u.w | Dictionary of registered client interest in data being processed i.e. (tables->(handle;syms) |
```suggestion
| .u.w | Dictionary of registered client interest in data being processed (for example, tables->(handle;syms) |
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +Functions are open source & open to customisation.
```suggestion
Functions are open source and open to customisation.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +* otherwise returns an empty table `x` (i.e. schema definition of table), with the [grouped attribute](../ref/set-attribute.md#grouped-and-parted) applied to the sym column.
```suggestion
* otherwise returns an empty table `x` (schema definition of table), with the [grouped attribute](../ref/set-attribute.md#grouped-and-parted) applied to the sym column.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +Each script should be run from the OS command prompt e.g.
```suggestion
Each script should be run from the OS command prompt as shown in the following example.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +The publisher will generate some random data and publish it periodically on a timer.
```suggestion
The publisher generates some random data and publishes it periodically on a timer.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/architecture/uq.md
> +The subscriber will receive data from the publisher and output it to the screen. You can modify the subscription request and the `upd` function of the subscriber as required. You can run multiple sub
```suggestion
The subscriber receives data from the publisher and is displayed on the screen. You can modify the subscription request and the `upd` function of the subscriber as required. You can run multiple subscribers at once.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/learn/startingkdb/hdb.md
> +The script :fontawesome-brands-github:[`KxSystems/cookbook/start/buildhdb.q`](https://github.com/KxSystems/cookbook/blob/master/start/buildhdb.q) will build a sample HDB.
```suggestion
The script :fontawesome-brands-github:[`KxSystems/cookbook/start/buildhdb.q`](https://github.com/KxSystems/cookbook/blob/master/start/buildhdb.q) builds a sample HDB. 
```

2024-08-02 17:12 UTC, natalietanner commented on docs/learn/startingkdb/hdb.md
> +It builds a month’s random data in directory `start/db`, and takes a few seconds to run.
```suggestion
It builds a month’s random data in directory `start/db`. 
```

2024-08-02 17:12 UTC, natalietanner commented on docs/ref/aj.md
>  !!! tip "There is no requirement for any of the join columns to be keys but the join will be faster on keys."
```suggestion
!!! tip "There is no requirement for any of the join columns to be keys but the join is faster on keys."
```

2024-08-02 17:12 UTC, natalietanner commented on docs/wp/capi/index.md
> +Above, the first argument following [`tick.q`](../../architecture/tickq.md) is the name of the table schema file to use. The second argument is the location where the tickerplant log file will be cre
```suggestion
Above, the first argument following [`tick.q`](../../architecture/tickq.md) is the name of the table schema file to use. The second argument is the location where the tickerplant log file is created and the value following the `-p` option is the port the tickerplant listens on. The C process uses this port number when initializing the connection. The final step in this setup is to create a kdb+ mock feedhandler process, which acts as the trade data source for the tickerplant. Below is a simple publishing process.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/wp/data-recovery.md
>  In a standard tick system, each kdb+ message will call a function named `upd`. Each process may have a different definition of this function. A TP will publish each time the `upd` function is called
```suggestion
In a standard tick system, each kdb+ message calls a function named `upd`. Each process may have a different definition of this function. A TP publishes each time the `upd` function is called (if its timer is not set to batch the data), and an RDB inserts the data into the relevant table.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/wp/data-recovery.md
> +It will then replay this tplog to recover all the data that has passed through the TP up to that point in the day. The replay is achieved using [`-11!`](../basics/internal.md#-11-streaming-execute),
```suggestion
Recovery of an RDB involves restarting the process. On startup, an RDB subscribes to a TP and receives the following information:
- message count ([`.u.i`](../architecture/tickq.md#variables)) 
- location of the tplog ([`.u.L`](../architecture/tickq.md#variables)). 

It then replays this tplog to recover all the data that has passed through the TP up to that point in the day. The replay is achieved using [`-11!`](../basics/internal.md#-11-streaming-execute), the streaming replay function. 
```

2024-08-02 17:12 UTC, natalietanner commented on docs/wp/data-recovery.md
> +[`-11!`](../basics/internal.md#-11-streaming-execute) is an internal function that will read each message in a tplog in turn, running the function `functioname` on the `(tablename;tabledata)` paramet
```suggestion
[`-11!`](../basics/internal.md#-11-streaming-execute) is an internal function that reads each message in a tplog in turn, running the function `functioname` on the `(tablename;tabledata)` parameters.
```

2024-08-02 17:12 UTC, natalietanner commented on docs/wp/data-recovery.md
>  In this section, we will focus on normal usage of the `-11!` function where the tplog is uncorrupted, and move on to discuss how to use it to recover from a corrupted tplog below in [_Replay errors_]
```suggestion
This section focuses on normal usage of the `-11!` function where the tplog is uncorrupted, and then discusses how to use it to recover from a corrupted tplog below in [_Replay errors_](#replay-errors).
```

2024-08-02 18:27 UTC, sshanks-kx commented
think that's all the changes made, thanks

2024-08-05 07:46 UTC, merged

2024-08-05 08:56 UTC, natalietanner commented
Morning Simon,

I have reviewed the draft site and published the site now, so this should be live shortly.

Thanks for the edits.

Natalie

From: Simon Shanks ***@***.***>
Sent: Friday, August 2, 2024 7:28 PM
To: KxSystems/docs ***@***.***>
Cc: Natalie Tanner ***@***.***>; Review requested ***@***.***>
Subject: Re: [KxSystems/docs] refactor (PR #325)

CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


@sshanks-kx<https://github.com/sshanks-kx> requested your review on: #325<https://github.com/KxSystems/docs/pull/325> refactor.

-
Reply to this email directly, view it on GitHub<https://github.com/KxSystems/docs/pull/325#event-13745369872>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/BB77XYS5GWTOVUXBAZ5O4N3ZPPFUJAVCNFSM6AAAAABLHZZHYCVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJTG42DKMZWHE4DOMQ>.
You are receiving this because your review was requested.Message ID: ***@***.***>

***********************************************************************************************************************************************************************
This email, its contents and any files attached are a confidential communication and are intended only for the named addressees indicated in the message. If you are not the named addressee or if you have received this email in error, you may not, without the consent of First Derivatives, copy, use or rely on any information or attachments in any way. Please notify the sender by return email and delete it from your email system.
Unless separately agreed, First Derivatives does not accept any responsibility for the accuracy or completeness of the contents of this email or its attachments. Please note that any views, opinion or advice contained in this communication are those of the sending individual and not those of First Derivatives and First Derivatives shall have no liability whatsoever in relation to this communication (or its content) unless separately agreed.
***********************************************************************************************************************************************************************